# fly.toml app configuration file generated for davivienda-hack-day-cr-2244 on 2025-05-15T11:34:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'davivienda-hack-day-cr-2244'
primary_region = 'gru'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1


  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  auto_start = true
  auto_stop = false
